### ISSUE TITLE
Make profile model configurable?

### ISSUE THREAD

**Issue by abendig** [stephenmcd/drum#15]
On a project I am working on, there is already a user profile that captures non-authentication user information, so the only really interesting new field that drum's `Profile` model provides is the `karma` field. We would prefer just using the one class. I'm considering adding a setting to drum, such that you can specify which Profile model it should use. The default would be the current one, but if specified otherwise, it could just access a different one.

Does that seem reasonable and if so, would you want that in the code?

**Comment by stephenmcd** [comment]
I think that's already the purpose of the `AUTH_PROFILE_MODULE` Django setting. So we could certainly remove hard-coded references to the `Profile` model in Drum, in fact Mezzanine already have a function `mezzanine.accounts.get_profile_model`.

The other aspect is the creation of Drum's profile model - which I don't believe you can avoid due to the fixed nature of DB migrations.

**Comment by abendig** [comment]
Hm, `AUTH_PROFILE_MODULE` is deprecated since Django 1.5. It's no longer mentioned in the settings documentation for 1.7 - https://docs.djangoproject.com/en/1.7/ref/settings/. I take it that that will live on as a Mezzanine-specific setting though?

I can get a branch ready with the changes to update the references to that model.

**Comment by stephenmcd** [comment]
That's the plan for now - so go right ahead, thanks a lot.

**Comment by abendig** [comment]
Hey @stephenmcd - curious what your thoughts are about the changes I proposed in the pull request.

**Comment by stephenmcd** [comment]
Merged it now, thanks again.
